import { ReactElement } from "react";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <body>
        <ul>
          <li>
            <Link href="/">Go to /</Link>
          </li>
          <li>
            <Link href="/app/subpage">Go to /subpage</Link>
          </li>
          <li>
            <Link href="/app/client">Go to /client</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
